# Generated by Django 4.2.3 on 2023-10-12 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visitapp', '0002_alldata_alter_visitor_options'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alldata',
        ),
        migrations.AlterModelTable(
            name='visitor',
            table='visitors_dt',
        ),
    ]
